function genPlots(figs, plotdir)
ensureFolder(plotdir);

for idx = 1:length(figs)
    if(~is_invalid_gui_obj_handle(figs(idx)))
        print(figs(idx), char(fullfile( plotdir, ...
            matlab.lang.makeValidName(...
            "Plot-"+...
            string(idx)+...
            "-"+...
            replace(...
            figs(idx).Name,...
            ' ',...
            '-'))...
            +".png")),...
            '-dpng', '-r600');
        close(figs(idx));
    end
end

end

