function genPlots(figs)

for idx = 1:length(figs)
    if(~is_invalid_gui_obj_handle(figs(idx)))
        print(figs(idx), char(...
            matlab.lang.makeValidName(...
            "Plot-"+...
            string(idx)+...
            "-"+...
            replace(...
            figs(idx).CurrentAxes.Title.String,...
            ' ',...
            '-'))...
            +".png"),...
            '-dpng', '-r1200');
        close(figs(idx));
    end
end

end

